<?php

require_once('string-reader.php');
require_once('parser-utils.php');
require_once('lexer-utils.php');
require_once('parser.php');
require_once('parser-number.php');
require_once('parser-fractional.php');
require_once('jlex.php');
require_once('lexer.lex.php');
require_once('lexer-binary.lex.php');
require_once('lexer-octal.lex.php');
require_once('lexer-decimal.lex.php');
require_once('lexer-hex.lex.php');
require_once('lexer-fractional.lex.php');
require_once('number.php');
require_once('stack.php');
require_once('tree.php');
require_once('port.php');
require_once('string.php');
require_once('symbol.php');
require_once('boolean.php');
require_once('pair.php');
require_once('vector.php');
require_once('evaluator.php');
